name: tesla
version: 1.0.0+1
publish_to: none
description: App with Otp & phone login.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_native_splash: ^2.2.4
  animated_text_kit: ^4.2.2
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  flutter_signin_button: ^2.0.0
  flutter_keyboard_visibility: ^5.3.0
  email_validator: ^2.0.1
  legacy_progress_dialog: ^0.1.2

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
